module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#FAFAF8',
        foreground: '#2D2D2D',
        card: '#ffffff',
        cardForeground: '#2D2D2D',
        popover: '#ffffff',
        popoverForeground: '#2D2D2D',
        primary: '#E63946',
        primaryForeground: '#ffffff',
        secondary: '#2D2D2D',
        secondaryForeground: '#ffffff',
        muted: '#F5E6D3',
        mutedForeground: '#6B6B6B',
        accent: '#D4AF37',
        accentForeground: '#2D2D2D',
        destructive: '#E63946',
        destructiveForeground: '#ffffff',
        border: 'rgba(45, 45, 45, 0.1)',
        input: 'transparent',
        inputBackground: '#ffffff',
        switchbackground: '#cbced4',
        fontweightmedium: 500,
        fontweightnormal: 400,
        ring: '#E63946',
        chart1: '#E63946',
        chart2: '#D4AF37',
        chart3: '#2D2D2D',
        chart4: '#F5E6D3',
        chart5: '#6B6B6B',
        radius: '0.5rem',
        sidebar: 'oklch(0.985, 0, 0)',
        sidebarforeground: 'oklch(0.145, 0, 0)',
        sidebarprimary: '#2D2D2D',
        sidebarprimaryforeground: 'oklch(0.985, 0, 0)',
        sidebaraccent: 'oklch(0.97, 0, 0)',
        sidebaraccentforeground: 'oklch(0.205, 0, 0)',
        sidebarborder: 'oklch(0.922, 0, 0)',
        sidebarring: 'oklch(0.708, 0, 0)',
        teal: '#006D5B',
        success: '#10B981',
        error: '#ef4444',
      },
      fontFamily: {
        heading: ['Playfair Display', 'serif'],
        body: ['Raleway', 'sans-serif'],
        accent: ['Cormorant', 'serif'],
      },
      keyframes: {
        logoSpinFade: {
          '0%': { opacity: 0, transform: 'rotate(-180deg) scale(0.9)' },
          '100%': { opacity: 1, transform: 'rotate(360deg) scale(1)' },
        },
        fadeIn: {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
      },
      animation: {
        logoSpinFade: 'logoSpinFade 1.5s ease-out forwards',
        'fade-in': 'fadeIn 1s ease-out forwards',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
      },
    },
  },
  plugins: [],
  darkMode: 'class', // match your .dark class
};